#!/usr/bin/env bash

set -x

DOTTY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER_BIN=${HOME}/bin
OS="`uname`"

mkdir -p ${USER_BIN}

if [ "${OS}" = "Linux" ]
then
   ln -sf "${DOTTY_DIR}/dotfiles/i3" ~/.i3
   ln -sf "${DOTTY_DIR}/dotfiles/terminal/i3_tab_title" ${USER_BIN}/tab_title
elif [ "${OS}" = "Darwin" ]
then
   defaults write com.apple.finder AppleShowAllFiles YES
   ln -sf "${DOTTY_DIR}/dotfiles/terminal/osx_tab_title" ${USER_BIN}/tab_title
fi

ln -sf "${DOTTY_DIR}/dotfiles/npm/npmrc" ${HOME}/.npmrc
